/*
 * ECU Main Entry Point
 * Project: Formula Student ECU
 * Architecture: Model B (Tick-Based Scheduler + DMA)
 */

#include "main.h"
#include "sensors.h"
#include "adc_driver.h"
#include "gpio_driver.h"
#include "timers.h"
#include <stdio.h>

// ===========================================================
// Global Variables (Managed by HAL/CubeMX)
// ===========================================================

ADC_HandleTypeDef hadc1;
DMA_HandleTypeDef hdma_adc1;

// ===========================================================
// Function Prototypes (Private)
// ===========================================================

void SystemClock_Config(void);
static void MX_GPIO_Init(void);
static void MX_DMA_Init(void);
static void MX_ADC1_Init(void);

// ===========================================================
// Main Function
// ===========================================================

int main(void)
{
    // -------------------------------------------------------
    // 1. Hardware Initialization (Low Level)
    // -------------------------------------------------------
    
    // Reset of all peripherals, Initializes the Flash interface and the Systick.
    HAL_Init();

    // Configure the system clock (CPU Speed)
    SystemClock_Config();

    // -------------------------------------------------------
    // 2. Peripheral Initialization (Generated by CubeMX)
    // -------------------------------------------------------
    
    // Initialize GPIO pins (Input/Output directions)
    MX_GPIO_Init();
    
    // Initialize DMA (Direct Memory Access) for background data transfer
    // IMPORTANT: DMA must be initialized BEFORE ADC!
    MX_DMA_Init();
    
    // Initialize ADC (Analog to Digital Converter)
    MX_ADC1_Init();

    // -------------------------------------------------------
    // 3. Driver & Software Initialization (Our Logic)
    // -------------------------------------------------------

    // SAFETY FIRST: Ensure all Injectors and Coils are OFF.
    // We don't want to accidentally fire anything during startup.
    gpio_init();

    // Start reading sensors in the background (DMA Circular Mode).
    // The "adc_raw_buffer" will now update automatically.
    adc_start();

    // Initialize the Task Scheduler (Set time to 0).
    timers_init();

    // -------------------------------------------------------
    // 4. Main Loop (The Scheduler)
    // -------------------------------------------------------
    
    while (1)
    {
        // We do NOT use HAL_Delay here.
        // We ask the scheduler: "Is it time to do something?"
        timers_update();

        // The CPU is free here most of the time.
        // Interrupts (Ignition/Injection) will interrupt this loop 
        // when the Crank Sensor signals.
    }
}

// ===========================================================
// System Configuration Functions (Standard CubeMX Output)
// ===========================================================

/**
  * @brief System Clock Configuration
  * @retval None
  * Note: This is usually generated by CubeMX based on your clock settings.
  */
void SystemClock_Config(void)
{
    // PLACEHOLDER: CubeMX will fill this part.
    // It sets up the PLL to run the STM32 at max speed (e.g., 168MHz).
    RCC_OscInitTypeDef RCC_OscInitStruct = {0};
    RCC_ClkInitTypeDef RCC_ClkInitStruct = {0};

    // ... Clock Config Code ...
}

/**
  * @brief ADC1 Initialization Function
  * @param None
  * @retval None
  */
static void MX_ADC1_Init(void)
{
    // PLACEHOLDER: CubeMX generates this.
    // Setup ADC1 for 14 channels, Scan Mode, DMA Continuous Requests.
    
    hadc1.Instance = ADC1;
    // ... ADC Config Code ...
    // HAL_ADC_Init(&hadc1);
}

/**
  * @brief DMA Initialization Function
  * @param None
  * @retval None
  */
static void MX_DMA_Init(void)
{
    // Enable DMA controller clock
    __HAL_RCC_DMA2_CLK_ENABLE();

    // DMA interrupt init
    // HAL_NVIC_SetPriority(DMA2_Stream0_IRQn, 0, 0);
    // HAL_NVIC_EnableIRQ(DMA2_Stream0_IRQn);
}

/**
  * @brief GPIO Initialization Function
  * @param None
  * @retval None
  */
static void MX_GPIO_Init(void)
{
    // PLACEHOLDER: CubeMX generates this.
    // Setup Injector and Coil pins as Output.
    
    /* GPIO Ports Clock Enable */
    __HAL_RCC_GPIOH_CLK_ENABLE();
    __HAL_RCC_GPIOA_CLK_ENABLE();
    __HAL_RCC_GPIOB_CLK_ENABLE();
}

/**
  * @brief  This function is executed in case of error occurrence.
  * @retval None
  */
void Error_Handler(void)
{
    // User can add his own implementation to report the HAL error return state
    __disable_irq();
    while (1)
    {
        // Blink a Red LED here if the system crashes
    }
}